name: Build FastAPI Matrix Images

on:
  schedule:
    - cron: '0 12,0 * * *'
  push:
    branches: [ main ]
    paths: [ 'fastapi/**', '.github/workflows/fastapi-matrix.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'fastapi/**', '.github/workflows/fastapi-matrix.yml' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write
  attestations: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: spjdevops/vardr/fastapi

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python_version: "3.12"
            distroless: "true"
            tag: "python3.12"
            base_image: "distroless"
            description: "Python 3.12 with Distroless runtime"
          - python_version: "3.13"
            distroless: "false"
            tag: "python3.13"
            base_image: "alpine"
            description: "Python 3.13 with Alpine runtime"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.tag }}
            type=sha,format=long

      - name: Build and push FastAPI image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./fastapi
          push: ${{ github.event_name != 'pull_request' }}
          target: ${{ matrix.base_image }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            DISTROLESS=${{ matrix.distroless }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate build provenance attestation
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Security scan
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() && github.event_name != 'pull_request' }}
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
