name: Build and Push Multiple Images

on:
  schedule:
    - cron: '0 12,0 * * *'   # Every day at 12:00 and 00:00 UTC
  push:
    branches: [ "main" ]
    paths: [ 'spring-boot/**', '.github/workflows/spring-boot.yml' ]
  pull_request:
    branches: [ "main" ]
    paths: [ 'spring-boot/**', '.github/workflows/spring-boot.yml' ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: spring-boot
            context: spring-boot
            tags: "latest,java21"
          # - name: fast-api
          #   context: fast-api
          #   tags: "latest,python13"

    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/vardr/${{ matrix.image.name }}
          tags: ${{ matrix.image.tags }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #cache-from: none
          #cache-to: none

      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ github.actor }}/vardr/${{ matrix.image.name }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Generate SBOM with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ github.actor }}/vardr/${{ matrix.image.name }}:latest
          format: 'cyclonedx'
          output: 'sbom-cyclonedx.json'
          command: 'fs'

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ github.actor }}/vardr/${{ matrix.image.name }}:latest
          format: spdx-json
          output-file: sbom-spdx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom-${{ matrix.image.name }}-latest
          path: |
            sbom-cyclonedx.json
            sbom-spdx.json
          retention-days: 90

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Install cosign for SBOM
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Attach SBOM to image
        if: github.event_name != 'pull_request'
        run: |
          cosign attach sbom --sbom sbom-cyclonedx.json ${{ env.REGISTRY }}/${{ github.actor }}/vardr/${{ matrix.image.name }}:latest
